apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build-demo
spec:
  source:
    git:
      url: https://github.com/dongjiang1989/knative-demo
      revision: master
  template:
    name: buildpack
    kind: BuildTemplate # (or ClusterBuildTemplate)
    arguments:
    - name: IMAGE
      value: docker.io/gswk/knative-build-demo